spring:
  application:
    name: spring-cloud-alibaba-nacos-account
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        # Nacos ??????????????? server-addr ?? Nacos ????????
        server-addr: 127.0.0.1:8848
        # ??? nacos ??? namespace???? public
        namespace: public
server:
  port: 10002
