spring:
  application:
    name: spring-cloud-alibaba-nacos-account
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        # server-addr 指定 Nacos 服务器主机和端口
        server-addr: 127.0.0.1:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public
server:
  port: 10002
